In [4]:

from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.preprocessing import LabelEncoder



In [5]:
import pandas as pd
df=pd.read_csv(r'C:\Users\elham\Desktop\excel2\IRIS.csv')

In [6]:
df.head(2)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa

In [7]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
x,y=df.iloc[:,:-1],df.iloc[:,-1]

In [41]:
y.dtype

dtype('int64')

In [11]:
x.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [12]:
y.head(2)

0    Iris-setosa
1    Iris-setosa
Name: species, dtype: object

In [19]:
y=LabelEncoder().fit_transform(y)
y[:9]


array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [20]:
x=x.astype('float32')

In [21]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float32
 1   sepal_width   150 non-null    float32
 2   petal_length  150 non-null    float32
 3   petal_width   150 non-null    float32
dtypes: float32(4)
memory usage: 2.5 KB


In [22]:
x.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [26]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)
x

array([[-9.00681257e-01,  1.03205729e+00, -1.34127235e+00,
        -1.31297672e+00],
       [-1.14301682e+00, -1.24957606e-01, -1.34127235e+00,
        -1.31297672e+00],
       [-1.38535297e+00,  3.37848425e-01, -1.39813817e+00,
        -1.31297672e+00],
       [-1.50652075e+00,  1.06445141e-01, -1.28440678e+00,
        -1.31297672e+00],
       [-1.02184904e+00,  1.26345992e+00, -1.34127235e+00,
        -1.31297672e+00],
       [-5.37177444e-01,  1.95766926e+00, -1.17067528e+00,
        -1.05003083e+00],
       [-1.50652075e+00,  8.00654531e-01, -1.34127235e+00,
        -1.18150365e+00],
       [-1.02184904e+00,  8.00654531e-01, -1.28440678e+00,
        -1.31297672e+00],
       [-1.74885619e+00, -3.56360346e-01, -1.34127235e+00,
        -1.31297672e+00],
       [-1.14301682e+00,  1.06445141e-01, -1.28440678e+00,
        -1.44444966e+00],
       [-5.37177444e-01,  1.49486327e+00, -1.28440678e+00,
        -1.31297672e+00],
       [-1.26418459e+00,  8.00654531e-01, -1.22754097e+00,
      

In [28]:
x.shape

(150, 4)

In [43]:
import numpy as np
print(np.unique(y))

[0 1 2]


In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print('x train',x_train.shape,'test x',x_test.shape,'y train',y_train.shape,'y test',y_test.shape)

x train (105, 4) test x (45, 4) y train (105,) y test (45,)


In [46]:
n_features=x_train.shape[1]
print(n_features)

4


In [50]:
model=Sequential()
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(n_features,)))
model.add(Dense(8,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(10,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(3,activation='softmax'))

model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

C:\Users\elham\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [56]:
model.fit(x_train,y_train,epochs=150,batch_size=30,verbose=1)

Epoch 1/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9681 - loss: 0.0905
Epoch 2/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9525 - loss: 0.1111
Epoch 3/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9559 - loss: 0.1012
Epoch 4/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9681 - loss: 0.0872
Epoch 5/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9492 - loss: 0.1092
Epoch 6/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9625 - loss: 0.0890
Epoch 7/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9614 - loss: 0.0890
Epoch 8/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9714 - loss: 0.0782
Epoch 9/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9592 - loss: 0.0962
Epoch 10/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9581 - loss: 0.0889
Epoch 11/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9819 - loss: 0.0816
Epoch 12/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9841 - lo

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9879 - loss: 0.0486
Epoch 70/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9746 - loss: 0.0555
Epoch 71/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9813 - loss: 0.0639
Epoch 72/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9879 - loss: 0.0449
Epoch 73/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9679 - loss: 0.0652
Epoch 74/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9879 - loss: 0.0612
Epoch 75/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9679 - loss: 0.0689
Epoch 76/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9779 - loss: 0.0610
Epoch 77/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9802 - loss: 0.0618
Epoch 78/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9813 - loss: 0.0550
Epoch 79/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9813 - loss: 0.0532
Epoch 80/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9802 - loss: 

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9840 - loss: 0.0522
Epoch 138/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9840 - loss: 0.0523
Epoch 139/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9906 - loss: 0.0490
Epoch 140/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9840 - loss: 0.0400
Epoch 141/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9840 - loss: 0.0452
Epoch 142/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9840 - loss: 0.0415
Epoch 143/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9840 - loss: 0.0453
Epoch 144/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9940 - loss: 0.0395
Epoch 145/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9840 - loss: 0.0493
Epoch 146/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9940 - loss: 0.0437 
Epoch 147/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9940 - loss: 0.0472
Epoch 148/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.99

In [57]:
model.evaluate(x_test,y_test,verbose=2)

2/2 - 0s - 36ms/step - accuracy: 0.9778 - loss: 0.0515


[0.05148854851722717, 0.9777777791023254]

In [58]:
y_predict=model.predict(x_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


In [59]:
y_predict

array([[9.99788582e-01, 6.79398727e-05, 1.43517143e-04],
       [9.99103189e-01, 2.53664533e-04, 6.43196807e-04],
       [9.99363363e-01, 2.21012466e-04, 4.15662187e-04],
       [1.17983152e-04, 3.25071275e-01, 6.74810708e-01],
       [9.99123871e-01, 2.99274834e-04, 5.76875522e-04],
       [7.88901525e-05, 5.37633803e-03, 9.94544864e-01],
       [2.30843245e-04, 9.97390330e-01, 2.37879879e-03],
       [2.77968198e-02, 9.59223151e-01, 1.29800197e-02],
       [5.60710134e-07, 1.04940329e-04, 9.99894500e-01],
       [9.99012470e-01, 2.95893988e-04, 6.91581634e-04],
       [1.31100023e-04, 4.46265899e-02, 9.55242395e-01],
       [5.05870674e-04, 9.91719961e-01, 7.77417934e-03],
       [9.99435127e-01, 2.32055158e-04, 3.32732568e-04],
       [1.00777070e-04, 9.99477446e-01, 4.21805744e-04],
       [9.99697328e-01, 7.46102669e-05, 2.28066085e-04],
       [4.78688617e-06, 7.39295036e-04, 9.99255955e-01],
       [4.09755157e-04, 9.98989999e-01, 6.00182102e-04],
       [9.99586880e-01, 6.20164

In [60]:
y_predict.shape

(45, 3)

In [64]:
y_predict[0]

array([9.9978858e-01, 6.7939873e-05, 1.4351714e-04], dtype=float32)

In [63]:
from numpy import argmax
classs=argmax(y_predict[0])
classs

0

In [65]:
y_test[0]

0