In [1]:
#Tokenization: Splitting text into individual words or tokens.
#Lowercasing: Converting all text to lowercase to treat words like "Apple" and "apple" the same.
#Removing Stop Words: Words like "the", "and", "is", etc., that don’t add much meaning.
#Removing Punctuation: We often remove punctuation as it's generally not needed for analysis.
#Stemming/Lemmatization: Reducing words to their root form (e.g., "running" -> "run").

In [5]:
import spacy
from nltk.corpus import stopwords
import string

In [15]:
nlp = spacy.load("en_core_web_sm")
# Sample text
text = "This is an example sentence, showcasing NLP preprocessing!"
doc=nlp(text.lower())


In [19]:
tokens=[token.text for token in doc if token.text]
tokens


['this',
 'is',
 'an',
 'example',
 'sentence',
 ',',
 'showcasing',
 'nlp',
 'preprocessing',
 '!']

In [20]:
tokens=[token.text for token in doc if token.text not in stopwords.words('english')]
tokens

['example', 'sentence', ',', 'showcasing', 'nlp', 'preprocessing', '!']

In [21]:
tokens=[token.text for token in doc if token.text not in stopwords.words('english') and token.text not in string.punctuation]
tokens

['example', 'sentence', 'showcasing', 'nlp', 'preprocessing']

In [30]:
#converts the list of text documents into a matrix of TF-IDF features
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()

x=vectorizer.fit_transform(tokens)

print(vectorizer.get_feature_names_out())

print(x.toarray())


['example' 'nlp' 'preprocessing' 'sentence' 'showcasing']
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [54]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import spacy
from nltk.corpus import stopwords
import string

In [55]:
documents = ["I love programming", "I hate bugs", "Coding is fun", "Debugging is annoying"]
labels = [1, 0, 1, 0]  # Labels indicating positive/negative sentiment
# Sample labeled data (labels: 1 = positive, 0 = negative)


doc3=[]
for doc in documents:
    doc1=nlp(doc.lower())
    doc2=[token.text for token in doc1 if token.text not in stopwords.words('english') and token.text not in string.punctuation]
    print(doc2)
    doc3.append(" ".join(doc2))
print(doc3)

['love', 'programming']
['hate', 'bugs']
['coding', 'fun']
['debugging', 'annoying']
['love programming', 'hate bugs', 'coding fun', 'debugging annoying']


In [56]:


from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()


x=vectorizer.fit_transform(doc3)
y=labels

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

classifier=LogisticRegression()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)
print(f'aacuracy:{accuracy_score(y_test,y_pred)}')


aacuracy:0.0


In [5]:
import torch 
import numpy as np
array=np.array([[5,6],[2,8]])
x=torch.tensor(array)
print(x)

tensor([[5, 6],
        [2, 8]], dtype=torch.int32)


# define a neural network using torch

In [7]:
import torch.nn as nn

# Define a simple neural network
class Neural(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(Neural,self).__init__()
        self.fc1=nn.Linear(input_size,hidden_size)
        self.relu=nn.ReLU()
        self.fc2=nn.Linear(hidden_size,output_size)
        
    def forward(self,x):
        x=self.fc1(x)
        x=self.relu(x)
        x=self.fc2(x)
        return x

In [18]:

input_tensor = torch.tensor([[1.0, 2.0, 3.0]])
output=model.forward(input_tensor)


tensor([[-0.6708,  0.8500]], grad_fn=<AddmmBackward0>)


In [22]:
# Initialize model
model = Neural(input_size=3, hidden_size=5, output_size=2)

# Loss function and optimizer
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)



In [27]:
# Sample training data (Batch size = 2)
X_train = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # Features
y_train = torch.tensor([0, 1])  # Class labels (NOT one-hot encoded!)


# Sample training loop
epochs=100 # Number of training iterations
for epoch in range(epochs):
    optimizer.zero_grad() # Reset gradients
    output=model(X_train)  # Forward pass
    loss=criterion(output,y_train) # Compute loss
    loss.backward() # Backpropagation 
    optimizer.step()  # Update weights
    
    if epoch%10==0:
        print(f'epoch {epoch},loss:{loss.item()}')
    
    
    
    

epoch 0,loss:0.12254390120506287
epoch 10,loss:0.09279361367225647
epoch 20,loss:0.0709526315331459
epoch 30,loss:0.055224377661943436
epoch 40,loss:0.04389578476548195
epoch 50,loss:0.03563286364078522
epoch 60,loss:0.02949199639260769
epoch 70,loss:0.024830393493175507
epoch 80,loss:0.021216748282313347
epoch 90,loss:0.018360242247581482


In [ ]:
# Save the entire model
torch.save(modelm,'')



In [32]:
# Save the entire model
torch.save(model, r'C:\Users\elham\Desktop\excel2\model')


In [33]:
# Save the model's state_dict, save parametrs and weight only without arthitecture of model
torch.save(model.state_dict(), r'C:\Users\elham\Desktop\excel2\model2')

In [36]:
# Load the model's state_dict
model = Neural(input_size=3, hidden_size=5, output_size=2)  # Define the model architecture
model.load_state_dict(torch.load(r'C:\Users\elham\Desktop\excel2\model2'))
model.eval() 

Neural(
  (fc1): Linear(in_features=3, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=2, bias=True)
)

# Define CNN using torch

In [16]:
import torch 
import torch.nn as nn

class Nuralcon(nn.Module):
    def __init__(self):
        super(Nuralcon,self).__init__()
        self.conv1=nn.Conv2d(in_channels=1,out_channels=16,kernel_size=5,padding=2)
        self.Relu1=nn.ReLU()
        self.pool1=nn.MaxPool2d(kernel_size=2,stride=2)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.relu2 = nn.ReLU()
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.dropout=nn.Dropout(0.25)
        self.flatten=nn.Flatten()
        self.fc1=nn.Linear(32 * 7 * 7,123)
        self.fc2=nn.Linear(123,10)
        
        
    def forward(self,x):
        x=self.pool1(self.Relu1(self.conv1(x)))
        x=self.pool2(self.relu2(self.conv2(x)))
        x=self.dropout(x)
        x=self.flatten(x)
        x=self.fc1(x)
        x=self.fc2(x)
        return x
    
model2=Nuralcon()

In [ ]:
its same as this one
model=models.Sequential()
model.add(layers.Conv2D(filters=16,kernel_size=(5,5),padding='same',activation='relu',input_shape=(28,28,1)))
model.add(layers.MaxPooling2D(pool_size=(2,2),strides=(2,2)))
model.add(layers.Conv2D(filters=32,kernel_size=(3,3),activation='relu',padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2,2),strides=(2,2)))
model.add(layers.Dropout(0.25))
model.add(layers.Flatten())
model.add(layers.Dense(123,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))